"""
This type stub file was generated by pyright.
"""

value_errors = ...
def check_error(err, io=...): # -> None:
    ...

class Passthrough(Exception):
    def __init__(self) -> None:
        ...
    


