"""
This type stub file was generated by pyright.
"""

class PackBuilder:
    def __init__(self, repo) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    def __len__(self):
        ...
    
    def add(self, oid): # -> None:
        ...
    
    def add_recur(self, oid): # -> None:
        ...
    
    def set_threads(self, n_threads):
        ...
    
    def write(self, path=...): # -> None:
        ...
    
    @property
    def written_objects_count(self):
        ...
    


