"""
This type stub file was generated by pyright.
"""

class Submodule:
    def __del__(self): # -> None:
        ...
    
    def open(self):
        """Open the repository for a submodule."""
        ...
    
    @property
    def name(self):
        """Name of the submodule."""
        ...
    
    @property
    def path(self):
        """Path of the submodule."""
        ...
    
    @property
    def url(self):
        """URL of the submodule."""
        ...
    
    @property
    def branch(self):
        """Branch that is to be tracked by the submodule."""
        ...
    
    @property
    def head_id(self): # -> Oid:
        """Head of the submodule."""
        ...
    


