"""
This type stub file was generated by pyright.
"""

def maybe_string(ptr): # -> None:
    ...

def to_bytes(s, encoding=..., errors=...): # -> bytes:
    ...

def to_str(s): # -> str:
    ...

def ptr_to_bytes(ptr_cdata): # -> bytes:
    """
    Convert a pointer coming from C code (<cdata 'some_type *'>)
    to a byte buffer containing the address that the pointer refers to.
    """
    ...

def strarray_to_strings(arr):
    ...

class StrArray:
    """A git_strarray wrapper

    Use this in order to get a git_strarray* to pass to libgit2 out of a
    list of strings. This has a context manager, which you should use, e.g.

        with StrArray(list_of_strings) as arr:
            C.git_function_that_takes_strarray(arr)
    """
    def __init__(self, l) -> None:
        ...
    
    def __enter__(self):
        ...
    
    def __exit__(self, type, value, traceback): # -> None:
        ...
    


class GenericIterator:
    """Helper to easily implement an iterator.

    The constructor gets a container which must implement __len__ and
    __getitem__
    """
    def __init__(self, container) -> None:
        ...
    
    def next(self):
        ...
    
    def __next__(self):
        ...
    


