site_name: GitBlog2

theme:
  name: material
  palette:
    scheme: default
    primary: custom
  favicon: images/favicon.svg
  logo: images/favicon-dark.svg
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
